lwinterface/panini

examples/simple_examples/_wss_manager.py
examples/simple_examples/async_wss_web_server.py
panini/nats_client/_asyncio_cli.py
panini/nats_client/nats_client.py

-subscribe with ssid in response
-unsubscribe by ssid
-wss-nats bridge as example
only for asyncio mode

Added dynamic subscribe/unsubscribe

---

README.md

:wrench: readme minor fix

---

README.md
tests/run_test.sh
tests/test_client_listen.py
tests/test_client_listen_response.py
tests/test_encoding.py
tests/test_listen.py
tests/test_logs.py
tests/test_logs_in_separate_process.py
tests/test_parameter_allocation_queue_group.py
tests/test_parameter_listen_subject_only_if_include.py
tests/test_publish.py
tests/test_reply_to.py
tests/test_request.py
tests/test_sync.py
tests/test_task.py
tests/test_timeout.py
tests/test_timer_task.py
tests/test_validators.py
tests/test_web_server.py
tests/test_web_server_separately.py
tests/test_wss.py

for now - tests are fully independent and can be run from everywhere inside the project with `pytest` command

make tests independent - to run it simply using pytest command

---

README.md

:coconut: few words about middlewares

---

panini/app.py
panini/test_client.py

Errors about panini initialization are now showing to the user

#46 - added error logging for panini testclient

---

README.md
examples/simple_examples/async_middleware.py
examples/simple_examples/async_nats_timeout_middleware.py
examples/simple_examples/async_publish.py
examples/simple_examples/async_publish_diff_datatypes.py
examples/simple_examples/async_publish_from_another_thread.py
examples/simple_examples/async_reply_to.py
examples/simple_examples/async_request.py
examples/simple_examples/async_request_diff_datatypes.py
examples/simple_examples/async_web_server.py
examples/simple_examples/sync_example.py
examples/simple_examples/sync_request.py
examples/simple_examples/validators.py
panini/utils/logger.py

get_logger default parameter and log.warning -> log.info in examples 

---

examples/simple_examples/async_listen_monitoring_middleware.py
panini/middleware/listen_monitoring.py

Use histograms for quantile calculations

Listen monitoring percentile

---

grafana_dashboard/panini_dashboard.json

:wrench: app selection fix #16

---

grafana_dashboard/panini_dashboard.json

1m default rate size changed to 15m

---

panini/test_client.py

#101 - added posibility to pass args and kwargs to TestClient run_panini

---

panini/middleware/reader_emulator_middleware.py
panini/middleware/writer_emulator_middleware.py

from warn logger to print for experimental warning in emulator

---

panini/nats_client/_asyncio_cli.py

From json to ujson

---

tests/test_wss.py

hotfix for test_wss - added sleep waiting for websockets

---

panini/validator.py

bool fields fix

---

panini/test_client.py
tests/emulator/test_event_storage_middleware.py
tests/test_client_listen.py
tests/test_client_listen_response.py
tests/test_diff_datatypes.py
tests/test_middleware.py
tests/test_publish.py
tests/test_reply_to.py
tests/test_request_listen_response.py
tests/test_task.py
tests/test_timer_task.py
tests/test_validators.py

- added `do_always_listen` parameter
- added another Thread for listening to subjects
- added possibility to switch to manual waiting (`do_always_listen`=False)
- fixed problems with `@client.listen`

Major TestClient fix

---

panini/nats_client.py

fixed silent error if response type is list

---

.gitignore
panini/app.py
panini/async_test_client.py
panini/http_server/http_server_app.py
panini/test_client.py
pytest.ini
requirements/defaults.txt
tests/async_test_client/conftest.py
tests/async_test_client/separate_file/main.py
tests/async_test_client/separate_file/test_main.py
tests/async_test_client/test_error_handling.py
tests/async_test_client/test_is_subject_matches_pattern.py
tests/async_test_client/test_listen.py
tests/async_test_client/test_panini.py
tests/async_test_client/test_panini2.py
tests/async_test_client/test_request.py
tests/async_test_client/test_wait.py
tests/separate_file/main.py
tests/separate_file/test_main.py
tests/test_diff_datatypes.py
tests/test_logs_in_separate_process.py
tests/test_web_server_separately.py

- use async request/publish in test_client
- use `*` in subjects
- use advanced `client.wait`, that naturally do not wait for a message, but run a while loop, and check, if subject was called needed count times

Implemented AsyncTestClient for better testing experience

---

panini/app.py
panini/http_server/http_server_app.py
setup.py

- added ability to use any parameters for aiohttp including ssl_context (for https)

updated to v0.5.2

---

panini/app.py
panini/http_server/http_server_app.py
setup.py

Added ability to use any parameters for aiohttp including ssl_context (for https)

Release v0.5.2

---

README.md

fix indentation in readme example code

Fix indent in README.md

---

examples/tracing_middleware_compose/Dockerfile
examples/tracing_middleware_compose/docker-compose.yml
examples/tracing_middleware_compose/receiver/app/main.py
examples/tracing_middleware_compose/sender/app/main.py
panini/middleware/tracing_middleware.py

Refactored tracing middleware
1. Added exception tracing
2. Added ability to add custom events
3. Added request/response data in panini to default trace events for a better understanding
4. Moved logic around a bit (to provide better readability)

Refactoring tracing middleware
